version: '3.8'

services:
  app:
    build:
      context: ../.
      dockerfile: Dockerfile-dev

    volumes:
      - ../.:/workspaces/online-dictionary

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    environment:
      MONGODB_CONNECTION_URI: "mongodb://localhost:27017?retryWrites=true&w=majority"
    
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db 

volumes:
  mongodb-data:
